#!/bin/bash

PULL_REQUESTS=$(curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer 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" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/mariofpalb/github-actions-test/pulls \
  | jq '.[] | select(.user.login=="mariofpalb") | .[].user.login' \
  )
# NO FUNCIONA EL SELECT DE ARRIBA
echo ${PULL_REQUESTS}